name: Sweet android plugin CI checker

on:
  push:
    branches-ignore:
      - main
      - develop
      - release/*
env:
  ASSISTANT_REPO: 'EzywAppSampleAndroid'
  ASSISTANT_REPO_PLACEHOLDER_BRANCH: 'develop'
  ASSISTANT_REPO_LOG_BRANCH: 'develop'
  ASSISTANT_REPO_OWNER: 'randytang2021'
  CURRENT_REPO: "${{ github.event.repository.name }}"
  DEBUG: true
jobs:
  sweet_android_plugin_ci_checker:

    runs-on: ubuntu-latest

    steps:


      - name: 'Debug: Tree pwd'
        continue-on-error: true
        if: env.DEBUG == 'true'
        run: |
          echo "pwd ---> $(pwd)"
          tree -L 3

      - uses: actions/checkout@v3
        name: 'B -> Checkout code -> 1: ${{env.CURRENT_REPO}}'
        with:
          path: "${{env.CURRENT_REPO}}"

      - name: 'A -> Build env -> 1: set up JDK 11'
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: 'Debug: Tree pwd'
        continue-on-error: true
        if: env.DEBUG == 'true'
        run: |
          echo "pwd ---> $(pwd)"
          tree -L 3

      - name: 'B -> Checkout code -> 2: ${{env.ASSISTANT_REPO}}'
        uses: actions/checkout@v3
        with:
          repository: "${{env.ASSISTANT_REPO_OWNER}}/${{env.ASSISTANT_REPO}}"
          path: "${{env.ASSISTANT_REPO}}"
          ref: "refs/heads/${{env.ASSISTANT_REPO_PLACEHOLDER_BRANCH}}"

      - name: 'Debug: Tree pwd'
        continue-on-error: true
        if: env.DEBUG == 'true'
        run: |
          echo "pwd ---> $(pwd)"
          tree -L 3
      - name: "C -> Assistant repo setup --> 1: bind ${{env.ASSISTANT_REPO}} with ${{env.CURRENT_REPO}}"
        run: |
          cd "./${ASSISTANT_REPO}"
          chmod +x gradlew
          if [ -n "$ANDROID_SDK_ROOT" ]; then
            echo "ANDROID_SDK_ROOT --> ${ANDROID_SDK_ROOT}"
          else
            echo "ANDROID_SDK_ROOT is not set up!"
            #in case ANDROID_SDK_ROOT is not set correctly
            touch local.properties
            echo "sdk.dir=/home/ubuntu/Android/Sdk" >>local.properties
          fi
          if [ "$RUNNER_OS" == "Linux" ]; then
               sed -i "s/ThisIsAPlaceHolder/${CURRENT_REPO}/g" settings.gradle
               sed -i "s/\/\/pluginSet/pluginSet/g" settings.gradle
          elif [ "$RUNNER_OS" == "macOS" ]; then
               sed -i '' "s/ThisIsAPlaceHolder/${CURRENT_REPO}/g" settings.gradle
               sed -i '' "s/\/\/pluginSet/pluginSet/g" settings.gradle
          else
               echo "$RUNNER_OS is not supported"
               exit 1
          fi
          cat settings.gradle

      - name: Build with Gradle
        run: |

          cd "./${ASSISTANT_REPO}"
          ./gradlew ":${CURRENT_REPO}:clean"
          ./gradlew :"${CURRENT_REPO}":build
          ./gradlew :"${CURRENT_REPO}":test
      - name: 'Z -> Clean up'
        run: |
          delete_file_list=(
            "${ASSISTANT_REPO}"
            "${CURRENT_REPO}}"
          )
          for file_txt in "${delete_file_list[@]}"; do
            if [ -f "./${file_txt}" ]; then
              rm "./${file_txt}"
            fi
          done

      - name: 'Debug: Tree pwd'
        continue-on-error: true
        if: env.DEBUG == 'true'
        run: |
          echo "pwd ---> $(pwd)"
          tree -L 3